name: hashtag
description: "CuzzyTech HashTag AI"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1
  flutter_native_splash: ^2.3.7
  flutter_svg: ^2.0.9
  get: ^4.6.6
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  image_cropper: ^4.0.1
  internet_connection_checker_plus: ^1.0.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  event_bus: ^2.0.0
  flutter_local_notifications: ^17.2.2
 

  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.4
  fluttertoast: ^8.0.8
  

  flutter_launcher_icons: ^0.13.1


  # Animation Libraries
  lottie:
  flutter_timezone: ^3.0.1
  provider: ^6.1.2
  logger: ^2.4.0
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0
  vibration: ^2.0.0
  sqflite: ^2.3.3+1
  filter_list: ^1.0.3
  #babstrap_settings_screen: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  win32: ^5.5.3
  build_runner:

flutter_native_splash:
  image: assets/images/hashtag.png
  # branding: assets/icons/3x/branding_light.png
  android: true
  ios: true
  # color_dark: 1F1B16
  color: "#F1FFEA"
  fullscreen: true
  android_12:
    image: assets/images/hashtag.png
    # branding: assets/icons/3x/branding_light.png
    # color_dark: 1F1B16
    color: "#F1FFEA"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/hashtag.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/raw/
    - assets/flags/
    - assets/lottie/
    - assets/json/
    - assets/categories/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Mulish
      fonts:
          - asset: assets/fonts/Mulish-Light.ttf
          - asset: assets/fonts/Mulish-SemiBold.ttf
